In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10]) 
np.mean(a)


np.float64(5.0)

In [3]:
### Create a rank-1 numpy array with 1 axes of length 3.
a = np.array([1, 2, 3])

### Print object type
print("type(a) =", type(a))

### Print shape
print("\na.shape =", a.shape)

### Print some values in a
print("\nValues in a: ", a[0], a[1], a[2])

### Create a 2x2 numpy array
b = np.array([[1, 2], [3, 4]])

### Print shape
print("\nb.shape =", b.shape)

## Print some values in b
print("\nValues in b: ", b[0, 0], b[0, 1], b[1, 1])

### Create a 3x2 numpy array
c = np.array([[1, 2], [3, 4], [5, 6]])

### Print shape
print("\nc.shape =", c.shape)

### Print some values in c
print("\nValues in c: ", c[0, 1], c[1, 0], c[2, 0], c[2, 1])

type(a) = <class 'numpy.ndarray'>

a.shape = (3,)

Values in a:  1 2 3

b.shape = (2, 2)

Values in b:  1 2 4

c.shape = (3, 2)

Values in c:  2 3 5 6


In [4]:
### 2x3 array containing zeros 
d = np.zeros((2, 3))
print("d =\n", d)

### 4x2 array of ones
e = np.ones((4, 2))
print("\ne =\n", e)

### 2x2 constant array
f = np.full((2, 2), 9)
print("\nf =\n", f)

### 3x3 random array
g = np.random.random((3, 3))
print("\ng =\n", g)

### 2x2 array with uninitialized values
h = np.empty((2, 2))
print("\nh =\n", h)

d =
 [[0. 0. 0.]
 [0. 0. 0.]]

e =
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

f =
 [[9 9]
 [9 9]]

g =
 [[0.77880069 0.70811328 0.79264523]
 [0.24547258 0.94744847 0.3043626 ]
 [0.9488335  0.119944   0.8750464 ]]

h =
 [[0. 0.]
 [0. 0.]]
